version: "3.8"
services:

  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./Gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./Gateway/api_gateway.conf:/etc/nginx/api_gateway.conf

  user-service:
    image: user-service:compose_build
    build:
      context: ./user-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: 8080

  post-service:
    image: post-service:compose_build
    build:
      context: ./post-service
      dockerfile: Dockerfile
    networks:
      - backend
    environment:
      PORT: 8080

networks:
  backend:
    name: backend
    driver: bridge