spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: none
    database-platform:
      org:
        hibernate:
          dialect: MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://db:3306/db_topalovic_app?createDatabaseIfNotExist=true&serverTimezone=Europe/Belgrade&useUnicode=true&characterEncoding=utf-8&connectionCollation=utf8_general_ci
    username: root
    password: password
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  jackson:
    serialization:
      fail-on-empty-beans: false
  flyway:
    baselineOnMigrate: true
  mail:
    host: mail.lilly021.com
    port: 2525
    username: test@lilly021.com
    password: Lilly021!
    properties:
      mail:
        smtp:
          auth: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  elasticsearch:
    home: /etc/elasticsearch
    clustername: elasticsearch
    host: elasticsearch
    port: 9200
  deeplink: http://localhost:9091 #http://domen:port  #example -> http://207.154.199.194:9090
  main:
    allow-bean-definition-overriding: true

document:
  productcategory:
    path: /home/user/Desktop/Work/images/             #/opt/images/
    filepath: file:/home/user/Desktop/Work/images/    #/opt/images/

server:
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always



