--INSERT INTO `product` (`name`,`description`, `product_category_id`, `brand_id`, `primary_image_url`, `price`, `active`, `new_added`, `on_sale`, `product_position`, `discount`, `discount_product_position`,`slug`,`sku`) VALUES ('Akapela', '<p>Ruza&nbsp;</p>', 1, 4, 'images/3-2021/ef06d68c6911d08c817b7e37a07ed694.png', 150, true, false, false, 1, 10, 10,'akapela-1','10001');
--INSERT INTO `product` (`name`,`description`, `product_category_id`, `brand_id`, `primary_image_url`, `price`, `active`, `new_added`, `on_sale`, `product_position`, `discount`, `discount_product_position`,`slug`,`sku`) VALUES ('Atina', '<p>Ruza&nbsp;</p>', 1, 5, 'images/3-2021/ef06d68c6911d08c817b7e37a07ed694.png', 150, true, false, false, 1, 10, 10,'akapela-1','10001');

INSERT INTO `product` (`name`,`description`, `product_category_id`, `brand_id`, `primary_image_url`, `price`, `active`, `new_added`, `on_sale`, `product_position`, `discount`, `discount_product_position`) VALUES ('Absurda', 'opis', 1, 1, 'images/12-2020/absurda.jpg', 19000, true, true, false, 2, 10, 9);
INSERT INTO `product` (`name`,`description`, `product_category_id`, `brand_id`, `primary_image_url`, `price`, `active`, `new_added`, `on_sale`, `product_position`, `discount`, `discount_product_position`) VALUES ('Fortuna', 'opis', 3, 1, 'images/12-2020/fortuna.jpg', 34000, true, true, false, 3, 10, 8);
INSERT INTO `product` (`name`,`description`, `product_category_id`, `brand_id`, `primary_image_url`, `price`, `active`, `new_added`, `on_sale`, `product_position`, `discount`, `discount_product_position`) VALUES ('Acuba japonica', 'opis', 3, 2, 'images/12-2020/jacuba.jpg', 22000, true, false, false, 4, 10, 7);
INSERT INTO `product` (`name`,`description`, `product_category_id`, `brand_id`, `primary_image_url`, `price`, `active`, `new_added`, `on_sale`, `product_position`, `discount`, `discount_product_position`) VALUES ('Juniperus', 'opis', 4, 2, 'images/12-2020/junuperus.jpeg', 14000, true, true, false, 5, 10, 6);
INSERT INTO `product` (`name`,`description`, `product_category_id`, `brand_id`, `primary_image_url`, `price`, `active`, `new_added`, `on_sale`, `product_position`, `discount`, `discount_product_position`) VALUES ('Cupressocyparis', 'opis', 4, 3, 'images/12-2020/kupres.jpg', 29000, true, true, false, 6, 10, 5);
INSERT INTO `product` (`name`,`description`, `product_category_id`, `brand_id`, `primary_image_url`, `price`, `active`, `new_added`, `on_sale`, `product_position`, `discount`, `discount_product_position`) VALUES ('Berberis', 'opis', 3, 2, 'images/12-2020/berberis.jpg', 54000, true, true, false, 7, 10, 4);
INSERT INTO `product` (`name`,`description`, `product_category_id`, `brand_id`, `primary_image_url`, `price`, `active`, `new_added`, `on_sale`, `product_position`, `discount`, `discount_product_position`) VALUES ('Rhododendron', 'opis', 4, 2, 'images/12-2020/rhododendron.jpg', 38000, true, true, false, 8, 10, 3);
INSERT INTO `product` (`name`,`description`, `product_category_id`, `brand_id`, `primary_image_url`, `price`, `active`, `new_added`, `on_sale`, `product_position`, `discount`, `discount_product_position`) VALUES ('Acer palmatum', 'opis', 5, 1, 'images/12-2020/acer.jpg', 23000, true, true, false, 9, 10, 2);
INSERT INTO `product` (`name`,`description`, `product_category_id`, `brand_id`, `primary_image_url`, `price`, `active`, `new_added`, `on_sale`, `product_position`, `discount`, `discount_product_position`) VALUES ('Magnolia', 'opis', 5, 3, 'images/12-2020/magnolija.jpg', 99000, true, true, false, 10, 10, 1);
