INSERT INTO `attribute` (`name`) VALUES ('Visina rasta');
INSERT INTO `attribute` (`name`) VALUES ('Širina rasta');
INSERT INTO `attribute` (`name`) VALUES ('Brzina rasta');
INSERT INTO `attribute` (`name`) VALUES ('Otpornost');
INSERT INTO `attribute` (`name`) VALUES ('Boja cveta');
INSERT INTO `attribute` (`name`) VALUES ('Vreme cvjetanja');
INSERT INTO `attribute` (`name`) VALUES ('Tip lista');
INSERT INTO `attribute` (`name`) VALUES ('Veličina cveta');
INSERT INTO `attribute` (`name`) VALUES ('Jačina mirisa');
INSERT INTO `attribute` (`name`) VALUES ('Dekorativnost');
INSERT INTO `attribute` (`name`) VALUES ('Osunčanost terena');
INSERT INTO `attribute` (`name`) VALUES ('Upotreba');
--INSERT INTO `attribute` (`name`) VALUES ('Boja lista');
